### ISSUE TITLE
Getting certificate verification error for danthes

### ISSUE THREAD

**Issue by azmatrana** [natify/danthes#29]
After updating my server ssl certificates. My site is working fine with updated SSL. But right after that my certificates I am getting error for any Danthes command. 

"Openssl (error=1, ----, statusl) certificate verification error"

I was using HTTPS protocol for the websockets now HTTPS is not working I changed the danthes to use HTTP protocol and it started working. 

I am using NGINX.
Ruby 2.2.1

```
danthes.yml

staging:
  adapter: puma
  server:  https://domain.com/faye
  secret_token: <%= ENV["DANTHES_SECRET"] %>
  signature_expiration: 600
  mount: '/faye'
```

This issue is only when I use HTTPS in protocol in danthes.yml.
